export const statusLabels = {
  pending: '待处理',
  queued: '排队中',
  claimed: '已领取',
  submitting: '提交中',
  running: '生产中',
  generating: '生成中',
  processing: '处理中',
  rendering: '渲染中',
  validating: '校验中',
  staging: '准备中',
  rebuilding: '重建中',
  uploading: '上传中',
  waiting_schedule: '等待定时发布',
  waiting_next_episode: '等待启动下一集',
  waiting_review: '待审核',
  waiting_asset_lock: '等待资产锁定',
  waiting_storyboard_image_review: '等待分镜图片审核',
  waiting_shot_video_review: '镜头视频分批待继续',
  ready_to_continue: '待继续',
  pending_review: '待审核',
  needs_review: '需审核',
  completed: '已完成',
  partially_failed: '部分失败',
  succeeded: '已生成',
  ready: '已就绪',
  valid: '有效',
  passed: '已通过',
  approved: '已通过',
  published: '已发布',
  reviewed: '已审核',
  aligned: '已对齐',
  active: '使用中',
  paused: '已暂停',
  locked: '已锁定',
  unlocked: '未锁定',
  healthy: '正常',
  warning: '有警告',
  degraded: '需关注',
  stale: '待更新',
  draft: '草稿',
  failed: '异常',
  invalid: '无效',
  conflicting: '有冲突',
  unhealthy: '异常',
  timeout: '已超时',
  rejected: '已拒绝',
  cancelled: '已取消',
  skipped: '已跳过',
  archived: '已归档',
  superseded: '已被替代',
  regenerated: '已重新生成',
  replaced: '已上传替换',
  removed: '已移除',
  dismissed: '已忽略',
  manual_required: '需人工处理',
  regenerating: '重新生成中',
  sent: '已发送',
}

export const statusTones = {
  completed: 'success', succeeded: 'success', ready: 'success', valid: 'success', passed: 'success',
  approved: 'success', published: 'success', reviewed: 'success', aligned: 'success', active: 'success',
  locked: 'success', healthy: 'success', regenerated: 'success', replaced: 'success',
  running: 'info', generating: 'info', processing: 'info', rendering: 'info', validating: 'info',
  staging: 'info', rebuilding: 'info', uploading: 'info', submitting: 'info', regenerating: 'info',
  waiting_review: 'warning', waiting_next_episode: 'warning', waiting_shot_video_review: 'warning',
  ready_to_continue: 'info', pending_review: 'warning', needs_review: 'warning', warning: 'warning',
  degraded: 'warning', stale: 'warning', conflicting: 'warning', manual_required: 'warning',
  partially_failed: 'warning', waiting_asset_lock: 'warning', waiting_storyboard_image_review: 'warning',
  failed: 'danger', invalid: 'danger', unhealthy: 'danger', timeout: 'danger', rejected: 'danger',
  pending: 'neutral', queued: 'neutral', claimed: 'neutral', paused: 'neutral', draft: 'neutral', cancelled: 'neutral',
  skipped: 'neutral', archived: 'neutral', superseded: 'neutral', removed: 'neutral', dismissed: 'neutral',
}

const valueLabels = {
  queued: '已排队',
  retry_queued: '等待重试',
  calling_model: '正在调用模型',
  window_validated: '章节窗口已校验',
  ready_for_reconcile: '等待合并发布',
  finished: '已结束',
  run: '执行',
  resume: '继续流程',
  retry: '重试',
  regenerate: '重新生成',
  review: '审核',
  create: '创建',
  update: '更新',
  approve: '通过',
  reject: '拒绝',
  text: '文本',
  upload: '上传文件',
  full: '完整版本',
  incremental: '增量版本',
  orchestrator: '流程总控',
  projects: '项目总控',
  stage2: '剧本与分镜阶段',
  stage3: '图片阶段',
  stage4: '视频与音频阶段',
  stage5: '剪辑与发布阶段',
  project: '项目',
  novel: '小说',
  novel_chunks: '文本分块',
  story_bible: '故事圣经',
  season_outline: '分集策划',
  episode: '剧集',
  episode_script: '单集剧本',
  storyboard: '分镜',
  visual_asset: '视觉资产',
  storyboard_image: '分镜图片',
  shot_video: '镜头视频',
  voice_profile: '角色音色',
  dialogue_audio: '对白音频',
  episode_master: '剧集成片',
  source_import: '原著导入',
  ir_extraction: '叙事信息提取',
  spec_validation: '改编规格校验',
  adaptation_compile: '改编计划编译',
  invalidation_scan: '修订影响扫描',
}

export function getStatusLabel(status) {
  return statusLabels[String(status || '').toLowerCase()] || '未知状态'
}

export function getDisplayValueLabel(value) {
  const normalized = String(value || '').toLowerCase().trim()
  return valueLabels[normalized] || (normalized ? '其他' : '—')
}
